[package]
name = "rust_bindgen_wasi"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[lib]
name = "rust_bindgen_wasi_lib"
path = "src/lib.rs"
crate-type =["cdylib"]

[dependencies]
rand = "0.7.3"
ssvm-wasi-helper = "=0.1.0"
wasmedge-bindgen = "0.4.0"
wasmedge-bindgen-macro = "0.4.0"
